<a href="https://colab.research.google.com/github/rishabh422tiwari/Summer-Training-ML/blob/main/Day1/Data%20Pre-processing/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [74]:
import numpy as np          # numpy is deal with numerical values
import matplotlib.pyplot as plt     #for ploting graphs and visualization
import pandas as pd                 # for manupliating and perform operations on dataframes

## Importing the dataset

In [75]:
dataset = pd.read_csv('/content/sample_data/Data.csv')
X = dataset.iloc[:, :-1].values       #Location by index   from starting index is 0,1,2,3 and from back it is -1,-2...
y = dataset.iloc[:, -1].values        # [row upper:row lower,col upper:col lower]

In [76]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [77]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [78]:
from sklearn.impute import SimpleImputer                             # sklearn function to fill missing values
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')     #creating object name "imputer"
imputer.fit(X[:, 1:3])                                               #fit our function on X
X[:, 1:3] = imputer.transform(X[:, 1:3])                             #transform means implement

In [79]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [80]:
from sklearn.compose import ColumnTransformer                        
from sklearn.preprocessing import OneHotEncoder                                                    #OneHotEncoder convert code to one 1 and rest of the catogory to zero ex: [0,1,0,0]
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')  # used passthrough because we want to encode col 1 but also want to retain rest of the col.
X = np.array(ct.fit_transform(X))

In [81]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [82]:
from sklearn.preprocessing import LabelEncoder      # encoding target col.
le = LabelEncoder()                                 # le is object of LabelEncoder
y = le.fit_transform(y)                             # conversion happened in this step

In [83]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [84]:
from sklearn.model_selection import train_test_split                                            # train_test_split for splitting to train data and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)    # function for train test split (if random state is same for two user on the same data both will have same data in train and test)
                                                                                                # test size usually done in 80 train & test but 70-30,90-10 can be seen also

In [85]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [86]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [87]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [88]:
print(y_test)

[0 1]


## Feature Scaling

In [93]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train[:, 3:] = scaler.fit_transform(X_train[:, 3:])
X_test[:, 3:] = scaler.transform(X_test[:, 3:])

In [96]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578537 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057581 -0.0701316764163542]
 [1.0 0.0 0.0 0.5667085065333245 0.6335624327104543]
 [0.0 0.0 1.0 -0.3045301939022482 -0.30786617274297856]
 [0.0 0.0 1.0 -1.9018011447007988 -1.4204636155515822]
 [1.0 0.0 0.0 1.147534306823706 1.2326533634535488]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200352 -0.5646194287757337]]


In [97]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830118 -0.9069571034860727]
 [1.0 0.0 0.0 -0.4497366439748436 0.20564033932252998]]


In [ ]:
# MinMaxScaler : scales all the data features in the range [0, 1] or else in the range [-1, 1] if there are negative values in the dataset
# StandardScaler : it makes mean = 0 and scales the data to unit (1) variance 