# Logistic Regression

## Importing the libraries

1.   List item
2.   List item



In [102]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [103]:
dataset = pd.read_csv('/content/sample_data/Company Bankruptcy.csv')
dataset.head()
dataset.shape

(1251, 96)

In [104]:
dataset.isnull().sum()

Bankrupt?                                                   0
 ROA(C) before interest and depreciation before interest    0
 ROA(A) before interest and % after tax                     0
 ROA(B) before interest and depreciation after tax          0
 Operating Gross Margin                                     0
                                                           ..
 Liability to Equity                                        1
 Degree of Financial Leverage (DFL)                         1
 Interest Coverage Ratio (Interest expense to EBIT)         1
 Net Income Flag                                            1
 Equity to Liability                                        1
Length: 96, dtype: int64

In [105]:
mean_values = dataset.iloc[:,1:].mean()

In [106]:
dataset.fillna(value=mean_values, inplace=True)

In [107]:
dataset.isnull().sum()

Bankrupt?                                                   0
 ROA(C) before interest and depreciation before interest    0
 ROA(A) before interest and % after tax                     0
 ROA(B) before interest and depreciation after tax          0
 Operating Gross Margin                                     0
                                                           ..
 Liability to Equity                                        0
 Degree of Financial Leverage (DFL)                         0
 Interest Coverage Ratio (Interest expense to EBIT)         0
 Net Income Flag                                            0
 Equity to Liability                                        0
Length: 96, dtype: int64

In [108]:
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values
print(X,y)

[[0.37059426 0.42438945 0.40574977 ... 0.56405011 1.         0.01646874]
 [0.46429094 0.53821413 0.51673002 ... 0.57017495 1.         0.02079431]
 [0.42607127 0.49901875 0.47229509 ... 0.56370608 1.         0.01647411]
 ...
 [0.4970994  0.55996511 0.55051127 ... 0.56611046 1.         0.03694707]
 [0.5080193  0.55609464 0.55222442 ... 0.56639454 1.         0.03587625]
 [0.48266953 0.53494331 0.53616361 ... 0.56537613 1.         0.03861187]] [1 1 1 ... 0 0 0]


## Splitting the dataset into the Training set and Test set

In [109]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [110]:
print(X_train)

[[0.36420806 0.41534017 0.4501847  ... 0.56508765 1.         0.01623757]
 [0.50129186 0.56454427 0.55222442 ... 0.56605917 1.         0.02711214]
 [0.52259543 0.56334496 0.56839231 ... 0.56538806 1.         0.02660542]
 ...
 [0.50095062 0.57757305 0.55591841 ... 0.56601654 1.         0.0345185 ]
 [0.46131721 0.47001744 0.51137641 ... 0.56486901 1.         0.04591756]
 [0.49929313 0.54900785 0.55243857 ... 0.5682606  1.         0.02454329]]


In [111]:
print(y_train)

[0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [112]:
print(X_test)

[[0.50563058 0.54889882 0.55201028 ... 0.56714691 1.         0.02193813]
 [0.56768878 0.6162778  0.60292307 ... 0.5652634  1.         0.03673174]
 [0.46531468 0.52654819 0.5112158  ... 0.62414742 1.         0.01711316]
 ...
 [0.50650807 0.56645225 0.55532951 ... 0.56617944 1.         0.02723809]
 [0.49134695 0.54966201 0.54130307 ... 0.56618157 1.         0.02703119]
 [0.48252328 0.5273659  0.5269554  ... 0.56636892 1.         0.16334666]]


In [113]:
print(y_test)

[0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


### [Feature Scaling](https://)

In [114]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [85]:
print(X_train)

[[-2.80627281e+00 -2.83601101e+00 -2.00876443e+00 ... -9.76498364e-03
   0.00000000e+00 -6.61239538e-01]
 [ 1.57175366e-01  3.31406628e-01  1.99579101e-01 ...  2.58673679e-02
   0.00000000e+00 -3.40050766e-01]
 [ 6.17711232e-01  3.05946932e-01  5.49484529e-01 ...  1.25302682e-03
   0.00000000e+00 -3.55017306e-01]
 ...
 [ 1.49798361e-01  6.07991508e-01  2.79524381e-01 ...  2.43039238e-02
   0.00000000e+00 -1.21298327e-01]
 [-7.06988044e-01 -1.67528033e+00 -6.84453486e-01 ... -1.77841809e-02
   0.00000000e+00  2.15381611e-01]
 [ 1.13967195e-01  1.58783819e-03  2.04213610e-01 ...  1.06609213e-01
   0.00000000e+00 -4.15923695e-01]]


In [115]:
print(X_test)

[[ 2.50968711e-01 -7.26679637e-04  1.94944592e-01 ...  6.57624941e-02
   0.00000000e+00 -4.92869112e-01]
 [ 1.59252971e+00  1.42964534e+00  1.29679910e+00 ... -3.31923569e-03
   0.00000000e+00 -5.59285262e-02]
 [-6.20571703e-01 -4.75202834e-01 -6.87929368e-01 ...  2.15637335e+00
   0.00000000e+00 -6.35378286e-01]
 ...
 [ 2.69938152e-01  3.71910690e-01  2.66779481e-01 ...  3.02785116e-02
   0.00000000e+00 -3.36330695e-01]
 [-5.78116288e-02  1.54749451e-02 -3.67808566e-02 ...  3.03566760e-02
   0.00000000e+00 -3.42441885e-01]
 [-2.48559894e-01 -4.57843950e-01 -3.47292958e-01 ...  3.72280987e-02
   0.00000000e+00  3.68373919e+00]]


## Training the Logistic Regression model on the Training set

In [116]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Predicting the Test set results

In [117]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]

## Making the Confusion Matrix

In [118]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[293   4]
 [ 10   6]]


0.9552715654952076

## Visualising the Training set results

## Visualising the Test set results

# Training the SVM model on the Training set

In [119]:
from sklearn.svm import SVC
classifier_linear = SVC(kernel = 'linear', random_state = 0)
classifier_linear.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

# Predicting the Test set results

In [120]:
y_pred_linear = classifier_linear.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred_linear),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]

# Making the Confusion Matrix

In [122]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_linear = confusion_matrix(y_test, y_pred)
print(cm_linear)
accuracy_score(y_test, y_pred)

[[293   4]
 [ 10   6]]


0.9552715654952076

# Visualising the Training set results SVM

# Visualising the Test set results SVM

## Training with SVM rbf kernel

In [123]:
from sklearn.svm import SVC
classifier_rbf = SVC(kernel = 'rbf', random_state = 0)
classifier_rbf.fit(X_train, y_train)

SVC(random_state=0)

## Predicting the Test set results

In [125]:
y_pred_rbf = classifier_rbf.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred_rbf),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]

## Making the Confusion Matrix

In [126]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_rbf = confusion_matrix(y_test, y_pred)
print(cm_rbf)
accuracy_score(y_test, y_pred)

[[293   4]
 [ 10   6]]


0.9552715654952076

## Visualising the Training set results

## Visualising the Test set results

## Training the SVM model on the Training set

In [127]:
from sklearn.svm import SVC
classifier_sigmoid = SVC(kernel = 'sigmoid', random_state = 0)
classifier_sigmoid.fit(X_train, y_train)

SVC(kernel='sigmoid', random_state=0)

## Predicting the Test set results

In [128]:
y_pred_sigmoid = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred_sigmoid),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]

## Making the Confusion Matrix

In [131]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_sigmoid = confusion_matrix(y_test, y_pred_sigmoid)
print(cm_sigmoid)
accuracy_score(y_test, y_pred)

[[293   4]
 [ 10   6]]


0.9552715654952076

## Visualising the Training set results

## Visualising the Test set results

## Training the SVM model on the Training set

In [132]:
from sklearn.svm import SVC
classifier_poly = SVC(kernel = 'poly', random_state = 0)
classifier_poly.fit(X_train, y_train)

SVC(kernel='poly', random_state=0)

## Predicting the Test set results

In [ ]:
y_pred_poly = classifier_poly.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred_poly),1), y_test.reshape(len(y_test),1)),1))

## Making the Confusion Matrix

In [134]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_poly = confusion_matrix(y_test, y_pred)
print(cm_poly)
accuracy_score(y_test, y_pred_poly)

[[293   4]
 [ 10   6]]


0.9456869009584664